// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using zad6_1.Data;

#nullable disable

namespace zad6_1.Migrations
{
    [DbContext(typeof(BookDBContext))]
    partial class BookDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("zad6_1.Data.Book", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<float>("Cost")
                        .HasColumnType("float");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.ToTable("books");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AuthorName = "J.K. Rowling",
                            Cost = 25.34f,
                            Image = "https://images-na.ssl-images-amazon.com/images/I/81iqZ2HHD-L.jpg",
                            Name = "Harry Potter: Philosopher's Stone",
                            PublishDate = new DateTime(1997, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2,
                            AuthorName = "J.K. Rowling",
                            Cost = 27.34f,
                            Image = "https://m.media-amazon.com/images/I/51mFoFmu0EL._AC_SY1000_.jpg",
                            Name = "Harry Potter: Chamber of Secrets",
                            PublishDate = new DateTime(1998, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 3,
                            AuthorName = "J.K. Rowling",
                            Cost = 25.34f,
                            Image = "https://image.ceneostatic.pl/data/products/35692256/i-harry-potter-and-the-prisoner-of-azkaban.jpg",
                            Name = "Harry Potter: Prisoner of Azkaban",
                            PublishDate = new DateTime(1999, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 4,
                            AuthorName = "J.K. Rowling",
                            Cost = 23.34f,
                            Image = "https://m.media-amazon.com/images/I/51rwzf9iytL._AC_SY780_.jpg",
                            Name = "Harry Potter: Goblet of Fire",
                            PublishDate = new DateTime(2000, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 5,
                            AuthorName = "J.K. Rowling",
                            Cost = 21.99f,
                            Image = "https://m.media-amazon.com/images/I/51lFAzVQUxL._AC_SY580_.jpg",
                            Name = "Harry Potter: Order of the Phoenix",
                            PublishDate = new DateTime(2003, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 6,
                            AuthorName = "J.K. Rowling",
                            Cost = 21.99f,
                            Image = "https://m.media-amazon.com/images/I/51nRdIU2qHL._AC_SY580_.jpg",
                            Name = "Harry Potter: Half-Blood Prince",
                            PublishDate = new DateTime(2005, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 7,
                            AuthorName = "J.K. Rowling",
                            Cost = 29.99f,
                            Image = "https://m.media-amazon.com/images/I/51RdS8EJEJL._AC_SY580_.jpg",
                            Name = "Harry Potter: Deathly Hallows",
                            PublishDate = new DateTime(2007, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 8,
                            AuthorName = "George Orwell",
                            Cost = 15.69f,
                            Image = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/1984first.jpg/220px-1984first.jpg",
                            Name = "Nineteen Eighty-Four",
                            PublishDate = new DateTime(1949, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 9,
                            AuthorName = "Frank Herbert",
                            Cost = 23.69f,
                            Image = "https://upload.wikimedia.org/wikipedia/en/thumb/d/de/Dune-Frank_Herbert_%281965%29_First_edition.jpg/220px-Dune-Frank_Herbert_%281965%29_First_edition.jpg",
                            Name = "Dune",
                            PublishDate = new DateTime(1965, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 10,
                            AuthorName = "Frank Herbert",
                            Cost = 23.69f,
                            Image = "https://upload.wikimedia.org/wikipedia/en/4/46/Dune_Messiah-Frank_Herbert_%281969%29_First_edition.jpg",
                            Name = "Dune Messiah",
                            PublishDate = new DateTime(1969, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 11,
                            AuthorName = "Frank Herbert",
                            Cost = 23.69f,
                            Image = "https://upload.wikimedia.org/wikipedia/en/a/a7/God_Emperor_of_Dune-Frank_Herbert_%281981%29_First_edition.jpg",
                            Name = "God Emperor of Dune",
                            PublishDate = new DateTime(1981, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 12,
                            AuthorName = "Frank Herbert",
                            Cost = 23.69f,
                            Image = "https://upload.wikimedia.org/wikipedia/en/d/de/Heretics_of_Dune-Frank_Herbert_%281984%29_First_edition.jpg",
                            Name = "Heretics of Dune",
                            PublishDate = new DateTime(1984, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 13,
                            AuthorName = "Frank Herbert",
                            Cost = 23.69f,
                            Image = "https://upload.wikimedia.org/wikipedia/en/8/82/Chapterhouse_Dune-Frank_Herbert_%281985%29_First_edition.jpg",
                            Name = "Chapterhouse: Dune",
                            PublishDate = new DateTime(1985, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 14,
                            AuthorName = "Frank Herbert",
                            Cost = 23.69f,
                            Image = "https://upload.wikimedia.org/wikipedia/en/6/67/Dune_House_Atreides_%281999%29.jpg",
                            Name = "Dune: House Atreides",
                            PublishDate = new DateTime(1985, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 15,
                            AuthorName = "Frank Herbert",
                            Cost = 23.69f,
                            Image = "https://upload.wikimedia.org/wikipedia/en/1/16/Dune_House_Harkonnen_%282000%29.jpg",
                            Name = "Dune: House Harkonnen",
                            PublishDate = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
